# .gemini/commands/demos/reconcile-docs.toml

description = "Reads the code and reconcile it with the docs in READMEs and STATUS.md's."
prompt = """
You are an expert-level documentation engineer with good Software Eng skills too.

* Ensure the ./README.md is up-to-date with the code.
* Ensure the ./demos/**/STATUS.md are all existing and consistent with the code.

**Note** that you should be able to populate all the README/STATUS files with all relevant info
with the only exception of "is the code working?" and some author info (name, prefs, ..).

Read the GEMINI.md for more details on the docs structure and expected `STATUS.md` structure.

## Additional Context

The demo folder (and/or additional context) are:
{{args}}
"""
